better code
ALazyMeme/FeelsOkayBot pull request #1
Opened 2022-03-28 12:08 UTC by nxxh447

2022-03-30 07:55 UTC, jammehcow requested changes
This is objectively not better code.

2022-03-30 10:35 UTC, nxxh447 commented
> This is objectively not better code.

run a performance test if you want.

2022-03-30 12:23 UTC, Felanbird commented on bot.js
> +	if (talkedRecently.has(msg.sendUserID) && !(msg.sendUserID === config.ownerID)) return; else {
Your chance of calling this better code died the moment you put an `else {` at the end of a line

2022-03-30 16:54 UTC, closed without merging

2022-04-08 10:21 UTC, ALazyMeme reviewed
While I appreciate your effort, my "scuffed" bot actually has some logic into the way I've made it. This includes personal preference with my OCD This repo is moreso people can see my work - no matter how good/bad it is, less so for people to make PRs.

2022-04-08 10:21 UTC, ALazyMeme commented on bot.js
> +const isUpperCase = (str) => { return (str === str.toUpperCase()) };
For someone who is fairly noobish at coding, I think "condensing" code just to preserve lines makes the readability far worse for myself.

2022-04-08 10:21 UTC, ALazyMeme commented on bot.js
> +"use strict";
My current solution of using backticks favours consistency over anything else.

2022-04-08 10:21 UTC, ALazyMeme commented on bot.js
> +	const prefixExists = String(msg.messageText).starsWith(config.prefix);
My comments were removed? What purpose did this serve?

2022-04-08 10:21 UTC, ALazyMeme commented on bot.js
> +client.on("PRIVMSG", (msg) => console.log(`[#${msg.channelName}] ${msg.displayName}: ${msg.messageText}`));
This is where it is now inconsistent.